# pulumi2nix library entry point.
#
# All functions take `pkgs` explicitly so the library stays system-agnostic
# and overlay-friendly.
{ lib }:
rec {
  # Nix system double -> Pulumi release target name.
  systemToTarget = {
    "x86_64-linux" = "linux-amd64";
    "aarch64-linux" = "linux-arm64";
    "x86_64-darwin" = "darwin-amd64";
    "aarch64-darwin" = "darwin-arm64";
  };

  # Parse a pulumi-lock.json (generated by pulumi2nix-lock) into an attrset.
  loadLock = lockFile:
    let lock = builtins.fromJSON (builtins.readFile lockFile);
    in assert lib.assertMsg (lock.version == 1)
      "pulumi2nix: unsupported pulumi-lock.json version ${toString lock.version}";
    lock;

  # Fetch one resource plugin release tarball as a fixed-output derivation
  # and unpack it into a directory shaped like a Pulumi plugin dir.
  fetchPlugin = import ./fetch-plugin.nix { inherit lib systemToTarget; };

  # Fetch the official pulumi/pulumi CLI release (CLI + bundled language hosts).
  fetchCli = import ./fetch-cli.nix { inherit lib systemToTarget; };

  # Synthesize the ~/.pulumi/plugins layout as a linkFarm.
  mkPluginStore = import ./plugin-store.nix { inherit lib; };

  # The main user-facing builder: lockFile + pythonEnv -> wrapped `pulumi`.
  mkPulumiEnv = import ./mk-pulumi-env.nix {
    inherit lib loadLock fetchPlugin fetchCli mkPluginStore systemToTarget;
  };
}
